/**
 * Booking Controller - Complete Implementation
 * Based on BOOKING_LOGIC_COMPLETE.md plan
 * Handles the full booking lifecycle from inquiry to completion
 */

const db = require("../db");
const emailService = require("../services/emailServiceNew");

/**
 * Create a new booking inquiry (Status: Inquiry Pending)
 * POST /api/bookings
 */
exports.createBookingInquiry = async (req, res) => {
  const userId = req.user.id;

  console.log('=== CREATE BOOKING INQUIRY ===');
  console.log('User ID:', userId);
  console.log('Request Body:', JSON.stringify(req.body, null, 2));

  const {
    tour_id,
    tier_id,
    travel_date,
    num_adults,
    num_children,
    participant_ages,
    selected_addons,
    selected_vehicles,
    estimated_price,
    contact_name,
    contact_email,
    contact_phone,
    contact_country,
    special_requests,
  } = req.body;

  console.log('Extracted values:', {
    tour_id,
    tier_id,
    travel_date,
    num_adults
  });

  // Validation
  if (!tour_id || !tier_id || !travel_date || !num_adults) {
    console.log('❌ Validation failed - missing required fields');
    return res.status(400).json({
      success: false,
      error: "Missing required fields: tour_id, tier_id, travel_date, num_adults",
    });
  }

  // Validate travel date (must be at least 5 days in the future)
  const travelDate = new Date(travel_date);
  const minDate = new Date();
  minDate.setDate(minDate.getDate() + 5);
  minDate.setHours(0, 0, 0, 0);
  travelDate.setHours(0, 0, 0, 0);

  if (isNaN(travelDate.getTime())) {
    return res.status(400).json({
      success: false,
      error: "Invalid travel date format. Please use YYYY-MM-DD.",
    });
  }

  if (travelDate < minDate) {
    return res.status(400).json({
      success: false,
      error: "Travel date must be at least 5 days in the future.",
      earliestDate: minDate.toISOString().split("T")[0],
    });
  }

  // Validate number of travelers
  if (num_adults < 1 || num_adults > 20) {
    return res.status(400).json({
      success: false,
      error: "Number of adults must be between 1 and 20.",
    });
  }

  if (num_children && (num_children < 0 || num_children > 10)) {
    return res.status(400).json({
      success: false,
      error: "Number of children must be between 0 and 10.",
    });
  }

  try {
    // Verify tour and tier exist
    const tourCheck = await db.query("SELECT id, name FROM tours WHERE id = $1", [tour_id]);
    if (tourCheck.rows.length === 0) {
      return res.status(404).json({
        success: false,
        error: "Tour not found.",
      });
    }

    const tierCheck = await db.query(
      "SELECT id, tier_name, price FROM packagetiers WHERE id = $1 AND tour_id = $2",
      [tier_id, tour_id]
    );
    if (tierCheck.rows.length === 0) {
      return res.status(404).json({
        success: false,
        error: "Package tier not found for this tour.",
      });
    }

    // Insert booking with status 'Inquiry Pending'
    // booking_reference will be auto-generated by trigger
    const insertQuery = `
      INSERT INTO bookings (
        user_id, tour_id, tier_id, travel_date,
        num_adults, num_children, participant_ages,
        selected_addons, selected_vehicles,
        estimated_price, currency, status,
        contact_name, contact_email, contact_phone, contact_country,
        special_requests, inquiry_date
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, NOW())
      RETURNING *
    `;

    const values = [
      userId,
      tour_id,
      tier_id,
      travel_date,
      num_adults || 1,
      num_children || 0,
      JSON.stringify(participant_ages || []),
      JSON.stringify(selected_addons || []),
      JSON.stringify(selected_vehicles || []),
      estimated_price,
      "INR",
      "Inquiry Pending",
      contact_name,
      contact_email,
      contact_phone,
      contact_country || null,
      special_requests || null,
    ];

    const result = await db.query(insertQuery, values);
    const booking = result.rows[0];

    // Send confirmation emails
    try {
      // Prepare booking data for emails
      const bookingData = {
        id: booking.id,
        user_id: userId,
        booking_reference: booking.booking_reference,
        tour_name: tourCheck.rows[0].name,
        tier_name: tierCheck.rows[0].tier_name,
        travel_date: booking.travel_date,
        num_adults: booking.num_adults,
        num_children: booking.num_children,
        estimated_price: booking.estimated_price,
        contact_name: booking.contact_name,
        contact_email: booking.contact_email,
        contact_phone: booking.contact_phone,
        special_requests: booking.special_requests,
        selected_addons: booking.selected_addons,
        selected_vehicles: booking.selected_vehicles,
        inquiry_date: booking.inquiry_date,
      };

      await emailService.sendInquiryConfirmationEmailToUser(bookingData);
      await emailService.sendNewInquiryEmailToAdmin(bookingData);
    } catch (emailError) {
      console.error("Error sending emails:", emailError);
      // Don't fail the booking if email fails
    }

    res.status(201).json({
      success: true,
      message: "Booking inquiry submitted successfully! Our team will respond within 30 minutes.",
      data: {
        id: booking.id,
        booking_reference: booking.booking_reference,
        status: booking.status,
        travel_date: booking.travel_date,
        estimated_price: booking.estimated_price,
      },
    });
  } catch (error) {
    console.error("Error creating booking:", error);
    res.status(500).json({
      success: false,
      error: "Failed to create booking inquiry. Please try again.",
    });
  }
};

/**
 * Get all bookings for the current user
 * GET /api/bookings/user
 */
exports.getUserBookings = async (req, res) => {
  const userId = req.user.id;

  try {
    const query = `
      SELECT
        b.*,
        t.name as tour_name,
        t.main_image_url as tour_image,
        t.duration_days,
        t.destinations as tour_destinations,
        pt.tier_name,
        pt.price as tier_price,
        r.rating as user_rating,
        r.id as review_id,
        CASE
          WHEN b.payment_timestamp IS NOT NULL AND
               b.status = 'Payment Confirmed' AND
               NOW() < (b.payment_timestamp + INTERVAL '24 hours')
          THEN true
          ELSE false
        END as can_cancel_with_refund
      FROM bookings b
      LEFT JOIN tours t ON b.tour_id = t.id
      LEFT JOIN packagetiers pt ON b.tier_id = pt.id
      LEFT JOIN reviews r ON b.tour_id = r.tour_id AND b.user_id = r.user_id
      WHERE b.user_id = $1
      ORDER BY b.created_at DESC
    `;

    const result = await db.query(query, [userId]);

    res.json({
      success: true,
      bookings: result.rows,
    });
  } catch (error) {
    console.error("Error fetching user bookings:", error);
    res.status(500).json({
      success: false,
      error: "Failed to fetch bookings.",
    });
  }
};

/**
 * Get booking details by ID
 * GET /api/bookings/:id
 */
exports.getBookingById = async (req, res) => {
  const { id } = req.params;
  const userId = req.user.id;

  try {
    const query = `
      SELECT
        b.*,
        t.name as tour_name,
        t.main_image_url as tour_image,
        t.duration_days,
        t.itinerary,
        pt.tier_name,
        pt.price as tier_price,
        pt.hotel_type,
        pt.inclusions_summary,
        pt.exclusions_summary,
        u.full_name as user_name,
        u.email as user_email,
        CASE
          WHEN b.payment_timestamp IS NOT NULL AND
               b.status = 'Payment Confirmed' AND
               NOW() < (b.payment_timestamp + INTERVAL '24 hours')
          THEN true
          ELSE false
        END as can_cancel_with_refund
      FROM bookings b
      LEFT JOIN tours t ON b.tour_id = t.id
      LEFT JOIN packagetiers pt ON b.tier_id = pt.id
      LEFT JOIN users u ON b.user_id = u.id
      WHERE b.id = $1 AND b.user_id = $2
    `;

    const result = await db.query(query, [id, userId]);

    if (result.rows.length === 0) {
      return res.status(404).json({
        success: false,
        error: "Booking not found.",
      });
    }

    const booking = result.rows[0];

    // ==================== ENRICHMENT: GET LATEST QUOTE REVISION ====================
    // Fetch the latest quote revision to get accurate pricing with discounts and fees
    const revisionResult = await db.query(
      `SELECT * FROM booking_quote_revisions
       WHERE booking_id = $1
       ORDER BY revision_number DESC
       LIMIT 1`,
      [id]
    );

    if (revisionResult.rows.length > 0) {
      const revision = revisionResult.rows[0];

      // Override booking prices with revision data (which includes discounts and fees)
      booking.final_price = revision.final_price;
      booking.base_price = revision.base_price;
      booking.vehicles_price = revision.vehicles_price;
      booking.addons_price = revision.addons_price;
      booking.subtotal_price = revision.subtotal_price;
      booking.total_discounts = revision.total_discounts;
      booking.total_fees = revision.total_fees;
      booking.discounts = revision.discounts;
      booking.additional_fees = revision.additional_fees;

      // Store complete revision data for reference
      booking.quote_revision = revision;
    }

    // ==================== ENRICHMENT: VEHICLES ====================
    if (booking.selected_vehicles && Array.isArray(booking.selected_vehicles)) {
      const enrichedVehicles = await Promise.all(
        booking.selected_vehicles.map(async (selectedVehicle) => {
          if (selectedVehicle.vehicle_id) {
            const vehicleResult = await db.query(
              'SELECT id, name, capacity, base_price_inr FROM vehicles WHERE id = $1',
              [selectedVehicle.vehicle_id]
            );

            if (vehicleResult.rows.length > 0) {
              const vehicleData = vehicleResult.rows[0];
              return {
                vehicle_id: selectedVehicle.vehicle_id,
                name: vehicleData.name,
                vehicle_name: vehicleData.name,
                quantity: selectedVehicle.quantity || 1,
                capacity: vehicleData.capacity,
                price: parseFloat(vehicleData.base_price_inr),
                original_price: parseFloat(vehicleData.base_price_inr)
              };
            }
          }
          return selectedVehicle;
        })
      );
      booking.selected_vehicles = enrichedVehicles;
    }

    // ==================== ENRICHMENT: ADDONS ====================
    if (booking.selected_addons && Array.isArray(booking.selected_addons)) {
      const enrichedAddons = await Promise.all(
        booking.selected_addons.map(async (selectedAddon) => {
          if (selectedAddon.addon_id) {
            const addonResult = await db.query(
              'SELECT id, name, price, description FROM addons WHERE id = $1',
              [selectedAddon.addon_id]
            );

            if (addonResult.rows.length > 0) {
              const addonData = addonResult.rows[0];
              return {
                addon_id: selectedAddon.addon_id,
                name: addonData.name,
                addon_name: addonData.name,
                quantity: selectedAddon.quantity || 1,
                price: parseFloat(addonData.price),
                description: addonData.description
              };
            }
          }
          return selectedAddon;
        })
      );
      booking.selected_addons = enrichedAddons;
    }

    res.json({
      success: true,
      data: booking,
    });
  } catch (error) {
    console.error("Error fetching booking:", error);
    res.status(500).json({
      success: false,
      error: "Failed to fetch booking details.",
    });
  }
};

/**
 * Cancel a booking (User)
 * POST /api/bookings/:id/cancel
 */
exports.cancelBooking = async (req, res) => {
  const { id } = req.params;
  const userId = req.user.id;

  try {
    // Get booking details
    const bookingResult = await db.query(
      "SELECT * FROM bookings WHERE id = $1 AND user_id = $2",
      [id, userId]
    );

    if (bookingResult.rows.length === 0) {
      return res.status(404).json({
        success: false,
        error: "Booking not found.",
      });
    }

    const booking = bookingResult.rows[0];

    // Check if already cancelled or completed
    if (booking.status === "Cancelled") {
      return res.status(400).json({
        success: false,
        error: "Booking is already cancelled.",
      });
    }

    if (booking.status === "Trip Completed") {
      return res.status(400).json({
        success: false,
        error: "Cannot cancel a completed trip.",
      });
    }

    // If payment confirmed, check 24-hour window
    if (booking.status === "Payment Confirmed") {
      const paymentTime = new Date(booking.payment_timestamp);
      const now = new Date();
      const hoursSincePayment = (now - paymentTime) / (1000 * 60 * 60);

      if (hoursSincePayment > 24) {
        return res.status(400).json({
          success: false,
          error: "The 24-hour free cancellation window has expired. Please contact us for assistance.",
          cancellation_deadline: new Date(paymentTime.getTime() + 24 * 60 * 60 * 1000).toISOString(),
        });
      }
    }

    // Update booking status to Cancelled
    await db.query(
      "UPDATE bookings SET status = $1, cancellation_date = NOW() WHERE id = $2",
      ["Cancelled", id]
    );

    // Send cancellation confirmation email
    try {
      // Fetch complete booking data with tour and tier info
      const updatedBookingResult = await db.query(
        `SELECT b.*, t.name as tour_name, t.duration_days,
                pt.tier_name, pt.price as tier_price
         FROM bookings b
         LEFT JOIN tours t ON b.tour_id = t.id
         LEFT JOIN packagetiers pt ON b.tier_id = pt.id
         WHERE b.id = $1`,
        [id]
      );

      if (updatedBookingResult.rows.length > 0) {
        const bookingData = updatedBookingResult.rows[0];
        // Add refund information
        bookingData.refund_eligible = booking.status === "Payment Confirmed";
        bookingData.refund_amount = bookingData.refund_eligible ? bookingData.final_price : 0;

        await emailService.sendCancellationEmailToUser(bookingData);
      }
    } catch (emailError) {
      console.error("Error sending cancellation email:", emailError);
      // Don't fail the operation if email fails
    }

    res.json({
      success: true,
      message: "Booking cancelled successfully.",
      refund_status: booking.status === "Payment Confirmed" ? "pending" : "not_applicable",
    });
  } catch (error) {
    console.error("Error cancelling booking:", error);
    res.status(500).json({
      success: false,
      error: "Failed to cancel booking.",
    });
  }
};

/**
 * Admin: Send quote to customer (Status: Quote Sent)
 * PUT /api/bookings/:id/send-quote
 * Admin only
 */
exports.sendQuote = async (req, res) => {
  const { id } = req.params;
  const { final_price, admin_notes } = req.body;

  if (!final_price) {
    return res.status(400).json({
      success: false,
      error: "Final price is required.",
    });
  }

  try {
    // Get booking
    const bookingResult = await db.query("SELECT * FROM bookings WHERE id = $1", [id]);

    if (bookingResult.rows.length === 0) {
      return res.status(404).json({
        success: false,
        error: "Booking not found.",
      });
    }

    const booking = bookingResult.rows[0];

    if (booking.status !== "Inquiry Pending") {
      return res.status(400).json({
        success: false,
        error: "Quote can only be sent for pending inquiries.",
      });
    }

    // Calculate quote expiration (48 hours from now)
    const quoteExpiration = new Date();
    quoteExpiration.setHours(quoteExpiration.getHours() + 48);

    // Update booking
    await db.query(
      `UPDATE bookings
       SET status = $1, final_price = $2, admin_notes = $3,
           quote_sent_date = NOW(), quote_expiration_date = $4
       WHERE id = $5`,
      ["Quote Sent", final_price, admin_notes, quoteExpiration, id]
    );

    // Send quote email to customer
    try {
      // Fetch complete booking data with tour and tier info
      const updatedBookingResult = await db.query(
        `SELECT b.*, t.name as tour_name, t.duration_days,
                pt.tier_name, pt.price as tier_price
         FROM bookings b
         LEFT JOIN tours t ON b.tour_id = t.id
         LEFT JOIN packagetiers pt ON b.tier_id = pt.id
         WHERE b.id = $1`,
        [id]
      );

      if (updatedBookingResult.rows.length > 0) {
        await emailService.sendQuoteEmailToUser(updatedBookingResult.rows[0]);
      }
    } catch (emailError) {
      console.error("Error sending quote email:", emailError);
      // Don't fail the operation if email fails
    }

    res.json({
      success: true,
      message: "Quote sent successfully to customer.",
      data: {
        quote_expiration: quoteExpiration,
        final_price,
      },
    });
  } catch (error) {
    console.error("Error sending quote:", error);
    res.status(500).json({
      success: false,
      error: "Failed to send quote.",
    });
  }
};

/**
 * Admin: Mark booking as completed (Status: Trip Completed)
 * PUT /api/bookings/:id/complete
 * Admin only
 */
exports.completeBooking = async (req, res) => {
  const { id } = req.params;
  const { admin_notes } = req.body;

  try {
    const bookingResult = await db.query("SELECT * FROM bookings WHERE id = $1", [id]);

    if (bookingResult.rows.length === 0) {
      return res.status(404).json({
        success: false,
        error: "Booking not found.",
      });
    }

    const booking = bookingResult.rows[0];

    if (booking.status !== "Payment Confirmed") {
      return res.status(400).json({
        success: false,
        error: "Only confirmed bookings can be marked as completed.",
      });
    }

    // Update booking
    await db.query(
      `UPDATE bookings
       SET status = $1, completion_date = NOW(), admin_notes = $2
       WHERE id = $3`,
      ["Trip Completed", admin_notes, id]
    );

    // Send review request email to customer
    try {
      // Fetch complete booking data with tour and tier info
      const updatedBookingResult = await db.query(
        `SELECT b.*, t.name as tour_name, t.duration_days,
                pt.tier_name, pt.price as tier_price
         FROM bookings b
         LEFT JOIN tours t ON b.tour_id = t.id
         LEFT JOIN packagetiers pt ON b.tier_id = pt.id
         WHERE b.id = $1`,
        [id]
      );

      if (updatedBookingResult.rows.length > 0) {
        await emailService.sendTripReviewRequestEmail(updatedBookingResult.rows[0]);
      }
    } catch (emailError) {
      console.error("Error sending review request email:", emailError);
      // Don't fail the operation if email fails
    }

    res.json({
      success: true,
      message: "Booking marked as completed. Review request email sent to customer.",
    });
  } catch (error) {
    console.error("Error completing booking:", error);
    res.status(500).json({
      success: false,
      error: "Failed to complete booking.",
    });
  }
};

/**
 * Admin: Get all bookings with filters
 * GET /api/admin/bookings
 * Admin only
 */
exports.getAllBookings = async (req, res) => {
  const { status, tour_id, start_date, end_date, page = 1, limit = 20 } = req.query;

  try {
    let query = `
      SELECT
        b.*,
        u.full_name as user_name,
        u.email as user_email,
        t.name as tour_name,
        pt.tier_name,
        CASE
          WHEN b.payment_timestamp IS NOT NULL AND
               b.status = 'Payment Confirmed' AND
               NOW() < (b.payment_timestamp + INTERVAL '24 hours')
          THEN true
          ELSE false
        END as can_cancel_with_refund,
        CASE
          WHEN b.quote_expiration_date IS NOT NULL AND
               b.status = 'Quote Sent' AND
               NOW() < b.quote_expiration_date
          THEN true
          ELSE false
        END as quote_is_valid
      FROM bookings b
      LEFT JOIN users u ON b.user_id = u.id
      LEFT JOIN tours t ON b.tour_id = t.id
      LEFT JOIN packagetiers pt ON b.tier_id = pt.id
      WHERE 1=1
    `;

    const params = [];
    let paramIndex = 1;

    if (status) {
      query += ` AND b.status = $${paramIndex}`;
      params.push(status);
      paramIndex++;
    }

    if (tour_id) {
      query += ` AND b.tour_id = $${paramIndex}`;
      params.push(tour_id);
      paramIndex++;
    }

    if (start_date) {
      query += ` AND b.travel_date >= $${paramIndex}`;
      params.push(start_date);
      paramIndex++;
    }

    if (end_date) {
      query += ` AND b.travel_date <= $${paramIndex}`;
      params.push(end_date);
      paramIndex++;
    }

    query += ` ORDER BY b.created_at DESC`;
    query += ` LIMIT $${paramIndex} OFFSET $${paramIndex + 1}`;
    params.push(limit, (page - 1) * limit);

    const result = await db.query(query, params);

    // Get total count for pagination
    const countQuery = `SELECT COUNT(*) FROM bookings WHERE 1=1`;
    const countResult = await db.query(countQuery);
    const totalCount = parseInt(countResult.rows[0].count);

    res.json({
      success: true,
      data: result.rows,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total: totalCount,
        pages: Math.ceil(totalCount / limit),
      },
    });
  } catch (error) {
    console.error("Error fetching bookings:", error);
    res.status(500).json({
      success: false,
      error: "Failed to fetch bookings.",
    });
  }
};

/**
 * Admin: Get booking statistics
 * GET /api/admin/bookings/stats
 * Admin only
 */
exports.getBookingStats = async (req, res) => {
  try {
    const statsQuery = `
      SELECT
        COUNT(*) FILTER (WHERE status = 'Inquiry Pending') as pending_count,
        COUNT(*) FILTER (WHERE status = 'Quote Sent') as quote_sent_count,
        COUNT(*) FILTER (WHERE status = 'Payment Confirmed') as confirmed_count,
        COUNT(*) FILTER (WHERE status = 'Cancelled') as cancelled_count,
        COUNT(*) FILTER (WHERE status = 'Trip Completed') as completed_count,
        COUNT(*) as total_count,
        COALESCE(SUM(CAST(final_price AS NUMERIC)) FILTER (WHERE status IN ('Payment Confirmed', 'Trip Completed')), 0) as total_revenue,
        COALESCE(AVG(CAST(final_price AS NUMERIC)) FILTER (WHERE status IN ('Payment Confirmed', 'Trip Completed')), 0) as avg_booking_value
      FROM bookings
    `;

    const result = await db.query(statsQuery);
    const rawStats = result.rows[0];

    // Transform to match frontend expectations
    const stats = {
      total: parseInt(rawStats.total_count) || 0,
      pending: parseInt(rawStats.pending_count) || 0,
      confirmed: parseInt(rawStats.confirmed_count) || 0,
      cancelled: parseInt(rawStats.cancelled_count) || 0,
      completed: parseInt(rawStats.completed_count) || 0,
      quote_sent: parseInt(rawStats.quote_sent_count) || 0,
      revenue: parseFloat(rawStats.total_revenue) || 0,
      avg_booking_value: parseFloat(rawStats.avg_booking_value) || 0,
    };

    res.json({
      success: true,
      data: stats,
    });
  } catch (error) {
    console.error("Error fetching booking stats:", error);
    res.status(500).json({
      success: false,
      error: "Failed to fetch booking statistics.",
    });
  }
};

/**
 * Admin: Get single booking by ID
 * GET /api/bookings/admin/:id
 * Admin only
 */
exports.getBookingByIdAdmin = async (req, res) => {
  const { id } = req.params;

  try {
    const result = await db.query(
      'SELECT * FROM booking_history_enriched WHERE id = $1',
      [id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({
        success: false,
        error: "Booking not found."
      });
    }

    res.status(200).json({
      success: true,
      data: result.rows[0]
    });
  } catch (error) {
    console.error(`Error fetching booking #${id}:`, error);
    res.status(500).json({
      success: false,
      error: "Internal server error"
    });
  }
};

/**
 * Admin: Delete a booking
 * DELETE /api/bookings/:id
 * Admin only
 */
exports.deleteBooking = async (req, res) => {
  const { id } = req.params;

  console.log('=== DELETE BOOKING REQUEST ===');
  console.log('Booking ID:', id);

  try {
    // Verify booking exists
    const bookingResult = await db.query(
      "SELECT * FROM bookings WHERE id = $1",
      [id]
    );

    if (bookingResult.rows.length === 0) {
      console.log('Booking not found');
      return res.status(404).json({
        success: false,
        error: "Booking not found."
      });
    }

    const booking = bookingResult.rows[0];
    console.log('Booking found:', { id: booking.id, status: booking.status });

    // Business rule: Can only delete if not confirmed or completed
    if (booking.status === 'Payment Confirmed' || booking.status === 'Trip Completed') {
      console.log('Cannot delete - booking is confirmed or completed');
      return res.status(400).json({
        success: false,
        error: `Cannot delete booking with status '${booking.status}'. Only Inquiry Pending, Under Review, Quote Sent, or Cancelled bookings can be deleted.`,
      });
    }

    // Delete the booking (CASCADE will handle related records)
    console.log('Deleting booking...');
    await db.query("DELETE FROM bookings WHERE id = $1", [id]);
    console.log('Booking deleted successfully');

    res.status(200).json({
      success: true,
      message: "Booking deleted successfully!",
    });
  } catch (error) {
    console.error(`Error deleting booking #${id}:`, error);
    res.status(500).json({
      success: false,
      error: "Internal server error",
      details: error.message
    });
  }
};

module.exports = {
  createBookingInquiry: exports.createBookingInquiry,
  getUserBookings: exports.getUserBookings,
  getBookingById: exports.getBookingById,
  cancelBooking: exports.cancelBooking,
  sendQuote: exports.sendQuote,
  completeBooking: exports.completeBooking,
  getAllBookings: exports.getAllBookings,
  getBookingStats: exports.getBookingStats,
  getBookingByIdAdmin: exports.getBookingByIdAdmin,
  deleteBooking: exports.deleteBooking,
};
